name            = "throwmyfile"
main            = "worker/index.ts"
compatibility_date = "2025-06-01"
account_id      = "8846c8d2c9e982da3cee1c655ff8cb7c"


[[containers]]
class_name   = "ThrowFilesContainer"
image        = "./Dockerfile"
max_instances = 3

[durable_objects]
bindings = [
  { name = "THROW_FILES_CONTAINER", class_name = "ThrowFilesContainer" }
]

[[migrations]]
tag               = "v1"
new_sqlite_classes = ["ThrowFilesContainer"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
